apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: solveai
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600
      containers:
        - image: IMAGE_PLACEHOLDER
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PUBLIC_DIR
              value: "/app/apps/backend/public"

            - name: GEMINI_PROJECT_ID
              value: "gen-lang-client-0102198071"
            - name: GEMINI_LIVE_WS_URL
              value: "wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContent"

            # Secret injected as env var
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GEMINI_API_KEY
                  key: latest
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
